// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyyh6IDhYg8AZKbRGcj8O9GStwifJ4dvI',
    appId: '1:245258508001:web:902d45407836b476ebc9a0',
    messagingSenderId: '245258508001',
    projectId: 'agrolinkbd-9d09f',
    authDomain: 'agrolinkbd-9d09f.firebaseapp.com',
    storageBucket: 'agrolinkbd-9d09f.firebasestorage.app',
    measurementId: 'G-JSSQQDF2CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmKkrTyCqPh50oqerMSx3ZzuhHyRUONtg',
    appId: '1:245258508001:android:ddc0654ca6007fb6ebc9a0',
    messagingSenderId: '245258508001',
    projectId: 'agrolinkbd-9d09f',
    storageBucket: 'agrolinkbd-9d09f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Replace when you add iOS app
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '245258508001',
    projectId: 'agrolinkbd-9d09f',
    storageBucket: 'agrolinkbd-9d09f.firebasestorage.app',
    iosBundleId: 'com.agrolinkbd.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Replace when you add macOS app
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '245258508001',
    projectId: 'agrolinkbd-9d09f',
    storageBucket: 'agrolinkbd-9d09f.firebasestorage.app',
    iosBundleId: 'com.agrolinkbd.app',
  );
}
