import 'dart:convert';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:agrolinkbd/core/services/admin_price_command_service.dart';

/// Single Actionable AI Price Recommendation
class AiPriceRecommendationItem {
  final String title;
  final String commodityOrCategory;
  final PriceCommandAction action;
  final PriceCommandScope scope;
  final String? targetCategory;
  final String? targetDivision;
  final String? targetDistrict;
  final double deltaPercent;
  final double currentAvgPrice;
  final double benchmarkPrice;
  final String urgency; // 'critical', 'high', 'moderate', 'normal'
  final String rationaleBn;
  final String rationaleEn;

  AiPriceRecommendationItem({
    required this.title,
    required this.commodityOrCategory,
    required this.action,
    required this.scope,
    this.targetCategory,
    this.targetDivision,
    this.targetDistrict,
    required this.deltaPercent,
    required this.currentAvgPrice,
    required this.benchmarkPrice,
    required this.urgency,
    required this.rationaleBn,
    required this.rationaleEn,
  });

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'commodityOrCategory': commodityOrCategory,
      'action': action.name,
      'scope': scope.name,
      'targetCategory': targetCategory,
      'targetDivision': targetDivision,
      'targetDistrict': targetDistrict,
      'deltaPercent': deltaPercent,
      'currentAvgPrice': currentAvgPrice,
      'benchmarkPrice': benchmarkPrice,
      'urgency': urgency,
      'rationaleBn': rationaleBn,
      'rationaleEn': rationaleEn,
    };
  }

  factory AiPriceRecommendationItem.fromMap(Map<String, dynamic> map) {
    return AiPriceRecommendationItem(
      title: map['title'] ?? 'বাজার সমন্বয় সুপারিশ',
      commodityOrCategory: map['commodityOrCategory'] ?? 'সার্বিক বাজার',
      action: PriceCommandAction.values.firstWhere(
        (a) => a.name == map['action'],
        orElse: () => PriceCommandAction.decrease,
      ),
      scope: PriceCommandScope.values.firstWhere(
        (s) => s.name == map['scope'],
        orElse: () => PriceCommandScope.all,
      ),
      targetCategory: map['targetCategory'],
      targetDivision: map['targetDivision'],
      targetDistrict: map['targetDistrict'],
      deltaPercent: (map['deltaPercent'] as num?)?.toDouble() ?? 5.0,
      currentAvgPrice: (map['currentAvgPrice'] as num?)?.toDouble() ?? 0.0,
      benchmarkPrice: (map['benchmarkPrice'] as num?)?.toDouble() ?? 0.0,
      urgency: map['urgency'] ?? 'moderate',
      rationaleBn: map['rationaleBn'] ?? '',
      rationaleEn: map['rationaleEn'] ?? '',
    );
  }
}

/// Comprehensive Market Intelligence Report Generated by AI
class AiMarketAnalysisReport {
  final String id;
  final String overviewBn;
  final String overviewEn;
  final int stabilityScore; // 0 - 100
  final String marketRiskLevel; // 'স্বাভাবিক', 'সতর্কতা', 'উচ্চ ঝুঁকি', 'সংকটপূর্ণ'
  final int totalProductsAnalyzed;
  final int totalFishLotsAnalyzed;
  final int recentOrdersAnalyzed;
  final double totalOrderVolumeBdt;
  final List<AiPriceRecommendationItem> recommendations;
  final DateTime timestamp;
  final String analysisEngine;

  AiMarketAnalysisReport({
    required this.id,
    required this.overviewBn,
    required this.overviewEn,
    required this.stabilityScore,
    required this.marketRiskLevel,
    required this.totalProductsAnalyzed,
    required this.totalFishLotsAnalyzed,
    required this.recentOrdersAnalyzed,
    required this.totalOrderVolumeBdt,
    required this.recommendations,
    required this.timestamp,
    required this.analysisEngine,
  });

  Map<String, dynamic> toMap() {
    return {
      'overviewBn': overviewBn,
      'overviewEn': overviewEn,
      'stabilityScore': stabilityScore,
      'marketRiskLevel': marketRiskLevel,
      'totalProductsAnalyzed': totalProductsAnalyzed,
      'totalFishLotsAnalyzed': totalFishLotsAnalyzed,
      'recentOrdersAnalyzed': recentOrdersAnalyzed,
      'totalOrderVolumeBdt': totalOrderVolumeBdt,
      'recommendations': recommendations.map((r) => r.toMap()).toList(),
      'timestamp': Timestamp.fromDate(timestamp),
      'analysisEngine': analysisEngine,
    };
  }

  factory AiMarketAnalysisReport.fromMap(Map<String, dynamic> map, String id) {
    return AiMarketAnalysisReport(
      id: id,
      overviewBn: map['overviewBn'] ?? '',
      overviewEn: map['overviewEn'] ?? '',
      stabilityScore: (map['stabilityScore'] as num?)?.toInt() ?? 75,
      marketRiskLevel: map['marketRiskLevel'] ?? 'স্বাভাবিক',
      totalProductsAnalyzed: (map['totalProductsAnalyzed'] as num?)?.toInt() ?? 0,
      totalFishLotsAnalyzed: (map['totalFishLotsAnalyzed'] as num?)?.toInt() ?? 0,
      recentOrdersAnalyzed: (map['recentOrdersAnalyzed'] as num?)?.toInt() ?? 0,
      totalOrderVolumeBdt: (map['totalOrderVolumeBdt'] as num?)?.toDouble() ?? 0.0,
      recommendations: (map['recommendations'] as List<dynamic>? ?? [])
          .map((item) => AiPriceRecommendationItem.fromMap(Map<String, dynamic>.from(item)))
          .toList(),
      timestamp: (map['timestamp'] as Timestamp?)?.toDate() ?? DateTime.now(),
      analysisEngine: map['analysisEngine'] ?? 'Gemini AI',
    );
  }
}

/// Masterclass AI Service for Automated Buying & Selling Price Analysis
class AiPriceAnalysisService {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  static String get _apiKey =>
      dotenv.env['GEMINI_API_KEY'] ?? dotenv.env['API_KEY'] ?? '';

  static final List<String> _modelCandidates = [
    'gemini-2.5-flash',
    'gemini-flash-latest',
    'gemini-2.0-flash',
    'gemini-1.5-flash',
    'gemini-1.5-pro',
  ];

  /// Run complete market analysis on live Buying & Selling data
  static Future<AiMarketAnalysisReport> runMarketAnalysis() async {
    debugPrint('🤖 Starting AI Buying & Selling Market Analysis...');

    // 1. Fetch live agricultural products
    final productsSnap = await _firestore
        .collection('products')
        .where('status', isEqualTo: 'active')
        .limit(100)
        .get()
        .catchError((_) => _firestore.collection('products').limit(100).get());

    // 2. Fetch live fish harvest lots
    final fishLotsSnap = await _firestore
        .collection('fish_marketplace_lots')
        .where('status', isEqualTo: 'active')
        .limit(100)
        .get()
        .catchError((_) => _firestore.collection('fish_marketplace_lots').limit(100).get());

    // 3. Fetch recent trade orders (Buying activity)
    final ordersSnap = await _firestore
        .collection('orders')
        .orderBy('createdAt', descending: true)
        .limit(50)
        .get()
        .catchError((_) => _firestore.collection('orders').limit(50).get());

    // 4. Fetch central benchmark rates
    final marketPricesSnap = await _firestore.collection('market_prices').get();

    // ─── Mathematical Aggregations ───────────────────────────
    final productDocs = productsSnap.docs;
    final fishDocs = fishLotsSnap.docs;
    final orderDocs = ordersSnap.docs;
    final benchmarkDocs = marketPricesSnap.docs;

    // Benchmarks lookup: name/category -> currentPrice
    final Map<String, double> benchmarkMap = {};
    for (final doc in benchmarkDocs) {
      final data = doc.data();
      final name = (data['productName'] ?? data['name'] ?? '').toString().toLowerCase();
      final category = (data['category'] ?? '').toString().toLowerCase();
      final price = (data['currentPrice'] ?? data['price'] ?? 0.0) as num;
      if (name.isNotEmpty) benchmarkMap[name] = price.toDouble();
      if (category.isNotEmpty) benchmarkMap[category] = price.toDouble();
    }

    // Product Category groups: category -> list of prices
    final Map<String, List<double>> cropCatPrices = {};
    for (final doc in productDocs) {
      final data = doc.data();
      final cat = (data['category'] ?? 'অন্যান্য').toString();
      final price = ((data['price'] ?? 0.0) as num).toDouble();
      if (price > 0) {
        cropCatPrices.putIfAbsent(cat, () => []).add(price);
      }
    }

    // Fish species groups
    final Map<String, List<double>> fishSpeciesPrices = {};
    for (final doc in fishDocs) {
      final data = doc.data();
      final species = (data['species'] ?? data['fishType'] ?? 'মাছ').toString();
      final price = ((data['pricePerKg'] ?? 0.0) as num).toDouble();
      if (price > 0) {
        fishSpeciesPrices.putIfAbsent(species, () => []).add(price);
      }
    }

    // Order Volume
    double totalOrderVolume = 0;
    for (final doc in orderDocs) {
      final data = doc.data();
      final amount = (data['totalAmount'] ?? data['amount'] ?? 0.0) as num;
      totalOrderVolume += amount.toDouble();
    }

    // Prepare Statistical Market Summary
    final buffer = StringBuffer();
    buffer.writeln('Market State Summary:');
    buffer.writeln('- Active Crop Listings: ${productDocs.length}');
    buffer.writeln('- Active Fish Lots: ${fishDocs.length}');
    buffer.writeln('- Recent Buyer Orders Evaluated: ${orderDocs.length}');
    buffer.writeln('- Total Trade Volume Evaluated: ৳${totalOrderVolume.toStringAsFixed(0)}');
    buffer.writeln('\nActive Crop Category Averages vs Benchmarks:');
    cropCatPrices.forEach((cat, prices) {
      final avg = prices.reduce((a, b) => a + b) / prices.length;
      final bench = benchmarkMap[cat.toLowerCase()] ?? benchmarkMap['সবজি'] ?? avg;
      final diffPct = bench > 0 ? ((avg - bench) / bench) * 100 : 0.0;
      buffer.writeln('  * $cat: Avg ৳${avg.toStringAsFixed(1)}, Benchmark ৳${bench.toStringAsFixed(1)}, Diff: ${diffPct.toStringAsFixed(1)}%');
    });

    buffer.writeln('\nFish Species Averages vs Benchmarks:');
    fishSpeciesPrices.forEach((species, prices) {
      final avg = prices.reduce((a, b) => a + b) / prices.length;
      final bench = benchmarkMap[species.toLowerCase()] ?? benchmarkMap['মাছ'] ?? avg;
      final diffPct = bench > 0 ? ((avg - bench) / bench) * 100 : 0.0;
      buffer.writeln('  * $species: Avg ৳${avg.toStringAsFixed(1)}, Benchmark ৳${bench.toStringAsFixed(1)}, Diff: ${diffPct.toStringAsFixed(1)}%');
    });

    final marketContext = buffer.toString();

    // ─── Try Gemini API Analysis ─────────────────────────────
    AiMarketAnalysisReport? aiReport;
    if (_apiKey.isNotEmpty) {
      for (final modelName in _modelCandidates) {
        try {
          final model = GenerativeModel(
            model: modelName,
            apiKey: _apiKey,
            systemInstruction: Content.system(_getSystemPrompt()),
            generationConfig: GenerationConfig(
              temperature: 0.2, // High factual consistency
              topK: 30,
              topP: 0.8,
              maxOutputTokens: 1200,
            ),
          );

          final response = await model.generateContent([
            Content.text('Please analyze this market data and output JSON:\n$marketContext'),
          ]);

          final text = response.text?.trim() ?? '';
          if (text.isNotEmpty) {
            aiReport = _parseGeminiResponse(
              text,
              productDocs.length,
              fishDocs.length,
              orderDocs.length,
              totalOrderVolume,
              modelName,
            );
            if (aiReport != null) break;
          }
        } catch (e) {
          debugPrint('⚠️ Gemini API Price Analysis failed on $modelName: $e');
        }
      }
    }

    // ─── Deterministic High-Precision Fallback (if offline or API key exhausted) ──
    aiReport ??= _generateDeterministicReport(
      productDocs.length,
      fishDocs.length,
      orderDocs.length,
      totalOrderVolume,
      cropCatPrices,
      fishSpeciesPrices,
      benchmarkMap,
    );

    // ─── Persist to Firestore for Audit & History ─────────────
    try {
      final docRef = await _firestore.collection('ai_price_recommendations').add(aiReport.toMap());
      // Also write latest trend snapshot
      await _firestore.collection('market_trend_analyses').doc('latest').set({
        'stabilityScore': aiReport.stabilityScore,
        'marketRiskLevel': aiReport.marketRiskLevel,
        'recommendationsCount': aiReport.recommendations.length,
        'updatedAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));

      return AiMarketAnalysisReport(
        id: docRef.id,
        overviewBn: aiReport.overviewBn,
        overviewEn: aiReport.overviewEn,
        stabilityScore: aiReport.stabilityScore,
        marketRiskLevel: aiReport.marketRiskLevel,
        totalProductsAnalyzed: aiReport.totalProductsAnalyzed,
        totalFishLotsAnalyzed: aiReport.totalFishLotsAnalyzed,
        recentOrdersAnalyzed: aiReport.recentOrdersAnalyzed,
        totalOrderVolumeBdt: aiReport.totalOrderVolumeBdt,
        recommendations: aiReport.recommendations,
        timestamp: aiReport.timestamp,
        analysisEngine: aiReport.analysisEngine,
      );
    } catch (e) {
      debugPrint('⚠️ Could not save ai_price_recommendations to Firestore: $e');
      return aiReport;
    }
  }

  /// System Prompt for Gemini
  static String _getSystemPrompt() {
    return '''
You are the Chief Market Economist and AI Agricultural Pricing Intelligence Engine of AgroLinkBD (Bangladesh).
Your duty is to analyze real-time buying and selling transactions, crop listings, fish harvest lots, and government benchmark prices across Bangladesh to prevent market crashes (বাজার ধস) and combat consumer inflation (অস্বাভাবিক মূল্যবৃদ্ধি).

Output ONLY valid raw JSON with no Markdown backticks or text formatting:
{
  "overviewBn": "সংক্ষিপ্ত বাংলা সারসংক্ষেপ (২-৩ বাক্য)",
  "overviewEn": "Brief English overview (2-3 sentences)",
  "stabilityScore": 78, // 0 to 100
  "marketRiskLevel": "স্বাভাবিক", // one of: "স্বাভাবিক", "সতর্কতা", "উচ্চ ঝুঁকি", "সংকটপূর্ণ"
  "recommendations": [
    {
      "title": "আলুর বাজার ধস রোধে কৃষক সুরক্ষা দর",
      "commodityOrCategory": "সবজি",
      "action": "increase", // "decrease", "increase", or "syncBenchmark"
      "scope": "category", // "all", "agri", "fish", "category", "division", or "district"
      "targetCategory": "সবজি",
      "targetDivision": null,
      "targetDistrict": null,
      "deltaPercent": 10.0, // max 25.0
      "currentAvgPrice": 22.5,
      "benchmarkPrice": 28.0,
      "urgency": "high", // "critical", "high", "moderate", "normal"
      "rationaleBn": "উৎপাদন খরচের নিচে বিক্রি রোধে ১০% দর সহায়তা প্রস্তাবিত।",
      "rationaleEn": "10% price support advised to protect farmers from selling below production cost."
    }
  ]
}
''';
  }

  /// Parse JSON from Gemini
  static AiMarketAnalysisReport? _parseGeminiResponse(
    String rawResponse,
    int productsCount,
    int fishLotsCount,
    int ordersCount,
    double totalVolume,
    String modelName,
  ) {
    try {
      String clean = rawResponse.replaceAll('```json', '').replaceAll('```', '').trim();
      final startIndex = clean.indexOf('{');
      final endIndex = clean.lastIndexOf('}');
      if (startIndex != -1 && endIndex != -1 && endIndex > startIndex) {
        clean = clean.substring(startIndex, endIndex + 1);
      }

      final Map<String, dynamic> data = jsonDecode(clean);
      final rawRecs = (data['recommendations'] as List<dynamic>? ?? []);
      final List<AiPriceRecommendationItem> recs = [];

      for (final r in rawRecs) {
        final map = Map<String, dynamic>.from(r);
        recs.add(AiPriceRecommendationItem.fromMap(map));
      }

      return AiMarketAnalysisReport(
        id: '',
        overviewBn: data['overviewBn'] ?? 'বাজারের ক্রয়-বিক্রয় পরিস্থিতি পর্যালোচনা করা হয়েছে।',
        overviewEn: data['overviewEn'] ?? 'Market trading and buying activity evaluated.',
        stabilityScore: (data['stabilityScore'] as num?)?.toInt() ?? 75,
        marketRiskLevel: data['marketRiskLevel'] ?? 'স্বাভাবিক',
        totalProductsAnalyzed: productsCount,
        totalFishLotsAnalyzed: fishLotsCount,
        recentOrdersAnalyzed: ordersCount,
        totalOrderVolumeBdt: totalVolume,
        recommendations: recs,
        timestamp: DateTime.now(),
        analysisEngine: 'Gemini AI ($modelName)',
      );
    } catch (e) {
      debugPrint('⚠️ Error parsing Gemini JSON: $e');
      return null;
    }
  }

  /// Grounded Deterministic Statistical Engine (Zero Hallucination Fallback)
  static AiMarketAnalysisReport _generateDeterministicReport(
    int productsCount,
    int fishLotsCount,
    int ordersCount,
    double totalVolume,
    Map<String, List<double>> cropCatPrices,
    Map<String, List<double>> fishSpeciesPrices,
    Map<String, double> benchmarkMap,
  ) {
    final List<AiPriceRecommendationItem> recommendations = [];
    int anomalyCount = 0;

    // Check crop categories
    cropCatPrices.forEach((category, prices) {
      if (prices.isEmpty) return;
      final avg = prices.reduce((a, b) => a + b) / prices.length;
      final bench = benchmarkMap[category.toLowerCase()] ?? benchmarkMap['সবজি'] ?? avg;
      if (bench <= 0) return;

      final diffPct = ((avg - bench) / bench) * 100;

      // Price Surge > 15% above benchmark -> Decrease recommendation
      if (diffPct > 15.0) {
        anomalyCount++;
        final delta = (diffPct * 0.7).clamp(5.0, 22.0);
        recommendations.add(
          AiPriceRecommendationItem(
            title: '$category ক্যাটাগরিতে অস্বাভাবিক মূল্যবৃদ্ধি নিয়ন্ত্রণ',
            commodityOrCategory: category,
            action: PriceCommandAction.decrease,
            scope: PriceCommandScope.category,
            targetCategory: category,
            deltaPercent: double.parse(delta.toStringAsFixed(1)),
            currentAvgPrice: double.parse(avg.toStringAsFixed(1)),
            benchmarkPrice: double.parse(bench.toStringAsFixed(1)),
            urgency: diffPct > 25 ? 'critical' : 'high',
            rationaleBn: '$category-এর গড় দর (৳${avg.toStringAsFixed(0)}/কেজি) সরকারি বাজার রেটের চেয়ে ${diffPct.toStringAsFixed(0)}% বেশি। ক্রেতা স্বার্থে $delta% দর কমানোর সুপারিশ।',
            rationaleEn: 'Average listing price is ${diffPct.toStringAsFixed(0)}% higher than benchmark. $delta% price reduction advised.',
          ),
        );
      }
      // Market Crash > 15% below benchmark -> Increase / Price Support recommendation
      else if (diffPct < -15.0) {
        anomalyCount++;
        final delta = (diffPct.abs() * 0.6).clamp(5.0, 20.0);
        recommendations.add(
          AiPriceRecommendationItem(
            title: '$category ক্যাটাগরিতে বাজার ধস রোধ ও কৃষক সুরক্ষা',
            commodityOrCategory: category,
            action: PriceCommandAction.increase,
            scope: PriceCommandScope.category,
            targetCategory: category,
            deltaPercent: double.parse(delta.toStringAsFixed(1)),
            currentAvgPrice: double.parse(avg.toStringAsFixed(1)),
            benchmarkPrice: double.parse(bench.toStringAsFixed(1)),
            urgency: diffPct.abs() > 25 ? 'critical' : 'high',
            rationaleBn: '$category-এর বর্তমান দর (৳${avg.toStringAsFixed(0)}/কেজি) বাজার রেটের চেয়ে ${diffPct.abs().toStringAsFixed(0)}% কম। কৃষকের ক্ষতি কমাতে $delta% দর সমন্বয় প্রয়োজন।',
            rationaleEn: 'Average listing price is ${diffPct.abs().toStringAsFixed(0)}% below benchmark. $delta% price support advised.',
          ),
        );
      }
    });

    // Check fish species
    fishSpeciesPrices.forEach((species, prices) {
      if (prices.isEmpty) return;
      final avg = prices.reduce((a, b) => a + b) / prices.length;
      final bench = benchmarkMap[species.toLowerCase()] ?? benchmarkMap['মাছ'] ?? avg;
      if (bench <= 0) return;

      final diffPct = ((avg - bench) / bench) * 100;

      if (diffPct > 15.0) {
        anomalyCount++;
        final delta = (diffPct * 0.65).clamp(5.0, 20.0);
        recommendations.add(
          AiPriceRecommendationItem(
            title: '$species মাছের দর সমন্বয় ও সাধারণ ক্রেতা স্বস্তি',
            commodityOrCategory: species,
            action: PriceCommandAction.decrease,
            scope: PriceCommandScope.fish,
            deltaPercent: double.parse(delta.toStringAsFixed(1)),
            currentAvgPrice: double.parse(avg.toStringAsFixed(1)),
            benchmarkPrice: double.parse(bench.toStringAsFixed(1)),
            urgency: 'high',
            rationaleBn: '$species মাছের পাইকারী দর (৳${avg.toStringAsFixed(0)}/কেজি) গড় হারের চেয়ে ${diffPct.toStringAsFixed(0)}% বেশি। $delta% দর সমন্বয় প্রস্তাবিত।',
            rationaleEn: '$species price is ${diffPct.toStringAsFixed(0)}% above benchmark. $delta% price reduction advised.',
          ),
        );
      } else if (diffPct < -15.0) {
        anomalyCount++;
        final delta = (diffPct.abs() * 0.6).clamp(5.0, 20.0);
        recommendations.add(
          AiPriceRecommendationItem(
            title: '$species চাষীদের উৎপাদন ক্ষতি রক্ষা সহায়তা',
            commodityOrCategory: species,
            action: PriceCommandAction.increase,
            scope: PriceCommandScope.fish,
            deltaPercent: double.parse(delta.toStringAsFixed(1)),
            currentAvgPrice: double.parse(avg.toStringAsFixed(1)),
            benchmarkPrice: double.parse(bench.toStringAsFixed(1)),
            urgency: 'high',
            rationaleBn: '$species মাছের দর অত্যধিক কমে যাওয়ায় খামারিরা ক্ষতিগ্রস্ত হচ্ছেন। $delta% দর সহায়তা প্রস্তাবিত।',
            rationaleEn: '$species price crashed by ${diffPct.abs().toStringAsFixed(0)}%. $delta% price support recommended.',
          ),
        );
      }
    });

    // If balanced, provide a stabilization recommendation
    if (recommendations.isEmpty) {
      recommendations.add(
        AiPriceRecommendationItem(
          title: 'বাজার স্থিতিশীল রয়েছে: বেঞ্চমার্ক সিঙ্ক সুপারিশ',
          commodityOrCategory: 'সামগ্রিক বাজার',
          action: PriceCommandAction.syncBenchmark,
          scope: PriceCommandScope.all,
          deltaPercent: 0.0,
          currentAvgPrice: 0.0,
          benchmarkPrice: 0.0,
          urgency: 'normal',
          rationaleBn: 'কৃষি ফসল ও মাছের গড় দর বর্তমানে সরকারি বেঞ্চমার্কের সাথে সামঞ্জস্যপূর্ণ রয়েছে। নতুন কোনো কৃত্রিম হস্তক্ষেপ প্রয়োজন নেই।',
          rationaleEn: 'Market prices currently align closely with benchmark rates. Zero intervention needed.',
        ),
      );
    }

    final int stabilityScore = (100 - (anomalyCount * 14)).clamp(35, 96);
    final String riskLevel = stabilityScore < 50
        ? 'উচ্চ ঝুঁকি'
        : stabilityScore < 75
            ? 'সতর্কতা'
            : 'স্বাভাবিক';

    return AiMarketAnalysisReport(
      id: '',
      overviewBn: 'মোট $productsCount টি ফসল, $fishLotsCount টি মাছের লট এবং $ordersCount টি সাম্প্রতিক ক্রয়-বিক্রয় অর্ডার বিশ্লেষণ করা হয়েছে। বাজারে $anomalyCount টি পণ্যে অস্বাভাবিক দর তারতম্য শনাক্ত হয়েছে।',
      overviewEn: 'Analyzed $productsCount crop listings, $fishLotsCount fish lots, and $ordersCount recent trade orders. Detected $anomalyCount pricing anomalies across the marketplace.',
      stabilityScore: stabilityScore,
      marketRiskLevel: riskLevel,
      totalProductsAnalyzed: productsCount,
      totalFishLotsAnalyzed: fishLotsCount,
      recentOrdersAnalyzed: ordersCount,
      totalOrderVolumeBdt: totalVolume,
      recommendations: recommendations,
      timestamp: DateTime.now(),
      analysisEngine: 'Grounded Real-Time Market Engine',
    );
  }

  /// Stream historical AI recommendations
  static Stream<List<AiMarketAnalysisReport>> streamHistoricalReports({int limit = 20}) {
    return _firestore
        .collection('ai_price_recommendations')
        .orderBy('timestamp', descending: true)
        .limit(limit)
        .snapshots()
        .map((snap) {
      return snap.docs.map((doc) => AiMarketAnalysisReport.fromMap(doc.data(), doc.id)).toList();
    });
  }
}
