import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:agrolinkbd/core/models/order_model.dart';
import 'package:flutter/foundation.dart';
import 'package:agrolinkbd/core/models/buyer_inventory_model.dart';
import 'package:agrolinkbd/core/services/buyer_inventory_service.dart';

class OrderService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final String _collectionName = 'orders';

  // Create a new order
  Future<String?> createOrder(OrderModel order) async {
    try {
      final docRef = await _firestore.collection(_collectionName).add(order.toMap());
      return docRef.id;
    } catch (e) {
      debugPrint('Error creating order: $e');
      return null;
    }
  }

  // Stream orders for a specific buyer
  Stream<List<OrderModel>> getOrdersByBuyerId(String buyerId) {
    return _firestore
        .collection(_collectionName)
        .where('buyerId', isEqualTo: buyerId)
        .snapshots()
        .map((snapshot) {
      final list = snapshot.docs.map((doc) {
        return OrderModel.fromMap(doc.data(), doc.id);
      }).toList();
      list.sort((a, b) => b.createdAt.compareTo(a.createdAt));
      return list;
    });
  }

  // Stream orders for a specific farmer
  Stream<List<OrderModel>> getOrdersByFarmerId(String farmerId) {
    return _firestore
        .collection(_collectionName)
        .where('farmerId', isEqualTo: farmerId)
        .snapshots()
        .map((snapshot) {
      final list = snapshot.docs.map((doc) {
        return OrderModel.fromMap(doc.data(), doc.id);
      }).toList();
      list.sort((a, b) => b.createdAt.compareTo(a.createdAt));
      return list;
    });
  }

  // Listen for new orders for a specific farmer (returns a stream of only newly added orders)
  Stream<OrderModel> listenToNewFarmerOrders(String farmerId) {
    // Only get orders created after this stream is initialized
    final now = DateTime.now();
    return _firestore
        .collection(_collectionName)
        .where('farmerId', isEqualTo: farmerId)
        // .where('createdAt', isGreaterThan: now) // requires composite index, simpler to just filter locally
        .snapshots()
        .expand((snapshot) => snapshot.docChanges)
        .where((change) => change.type == DocumentChangeType.added)
        .map((change) {
          final data = change.doc.data() as Map<String, dynamic>;
          return OrderModel.fromMap(data, change.doc.id);
        })
        .where((order) => order.createdAt.isAfter(now)); // Local filter
  }

  // Update order status
  Future<bool> updateOrderStatus(String orderId, String newStatus, int step) async {
    try {
      await _firestore.collection(_collectionName).doc(orderId).update({
        'status': newStatus,
        'statusStep': step,
      });

      // If the order is delivered (step == 4), add the item to Buyer's My Shop inventory
      if (step == 4) {
        // Fetch order details
        final docSnap = await _firestore.collection(_collectionName).doc(orderId).get();
        if (docSnap.exists) {
          final orderData = OrderModel.fromMap(docSnap.data()!, docSnap.id);
          
          final buyerInventoryService = BuyerInventoryService();
          final purchasePricePerUnit = orderData.quantity > 0 ? (orderData.totalAmount / orderData.quantity) : 0.0;
          
          final inventoryItem = BuyerInventoryModel(
            id: '', // Generated by Firestore
            buyerId: orderData.buyerId,
            productId: 'product_${DateTime.now().millisecondsSinceEpoch}', // Placeholder since OrderModel doesn't store original productId
            productName: orderData.productName,
            category: 'Category', // Placeholder
            quantity: orderData.quantity,
            unit: 'kg', // Default or parse from productName/details
            purchasePrice: purchasePricePerUnit,
            currentMarketPrice: purchasePricePerUnit, // Initially same
            location: 'Delivered Location', // Placeholder
            status: 'In Stock',
            image: orderData.productImageUrl,
            purchaseDate: DateTime.now(),
            updatedAt: DateTime.now(),
            supplierId: orderData.farmerId,
            supplierName: orderData.farmerName,
          );

          await buyerInventoryService.addToInventory(inventoryItem);
        }
      }

      return true;
    } catch (e) {
      debugPrint('Error updating order status: $e');
      return false;
    }
  }

  Future<void> updateOrderRating(String orderId, double rating, String reviewText) async {
    try {
      await _firestore.collection('orders').doc(orderId).update({
        'rating': rating,
        'reviewText': reviewText,
      });
    } catch (e) {
      debugPrint('Error updating order rating: $e');
    }
  }

  // Stream a single order by ID
  Stream<OrderModel?> getOrderByIdStream(String orderId) {
    return _firestore
        .collection(_collectionName)
        .doc(orderId)
        .snapshots()
        .map((doc) {
      if (doc.exists && doc.data() != null) {
        return OrderModel.fromMap(doc.data()!, doc.id);
      }
      return null;
    });
  }
}
