import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';

import 'pdf_theme_service.dart';

class ReportGeneratorUtils {
  
  static pw.Widget buildHeader({
    required String title,
    required String subtitle,
    String? dateRange,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('AgroLinkBD', 
                  style: pw.TextStyle(
                    fontSize: 28, 
                    fontWeight: pw.FontWeight.bold,
                    color: PdfThemeService.primaryColor,
                  )
                ),
                pw.SizedBox(height: 4),
                pw.Text('Connecting Farmers and Buyers', 
                  style: pw.TextStyle(
                    fontSize: 12,
                    color: PdfThemeService.subtextColor,
                    fontStyle: pw.FontStyle.italic,
                  )
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'Date: ${DateFormat('MMM dd, yyyy').format(DateTime.now())}',
                  style: pw.TextStyle(fontSize: 10, color: PdfThemeService.subtextColor),
                ),
                if (dateRange != null) ...[
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'Period: $dateRange',
                    style: pw.TextStyle(fontSize: 10, color: PdfThemeService.subtextColor),
                  ),
                ]
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 24),
        pw.Divider(color: PdfThemeService.borderColor, thickness: 1.5),
        pw.SizedBox(height: 16),
        pw.Text(title, 
          style: pw.TextStyle(
            fontSize: 20, 
            fontWeight: pw.FontWeight.bold,
            color: PdfThemeService.textColor,
          )
        ),
        if (subtitle.isNotEmpty) ...[
          pw.SizedBox(height: 6),
          pw.Text(subtitle, 
            style: pw.TextStyle(
              fontSize: 12, 
              color: PdfThemeService.subtextColor,
            )
          ),
        ],
        pw.SizedBox(height: 20),
      ],
    );
  }

  static pw.Widget buildFooter(pw.Context context) {
    return pw.Column(
      mainAxisSize: pw.MainAxisSize.min,
      children: [
        pw.Divider(color: PdfThemeService.borderColor, thickness: 1),
        pw.SizedBox(height: 8),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by AgroLinkBD System',
              style: pw.TextStyle(fontSize: 10, color: PdfThemeService.subtextColor),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(fontSize: 10, color: PdfThemeService.subtextColor),
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget buildSummaryCard(String title, String value, {PdfColor? color}) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: color?.shade(0.1) ?? PdfThemeService.backgroundColor,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        border: pw.Border.all(color: color?.shade(0.3) ?? PdfThemeService.borderColor),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(fontSize: 11, color: PdfThemeService.subtextColor),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 18, 
              fontWeight: pw.FontWeight.bold,
              color: color ?? PdfThemeService.primaryColor,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget buildTable({
    required List<String> headers,
    required List<List<String>> data,
    List<double>? columnWidths,
  }) {
    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: data,
      border: pw.TableBorder.all(color: PdfThemeService.borderColor, width: 0.5),
      headerStyle: pw.TextStyle(
        color: PdfThemeService.textColor, 
        fontWeight: pw.FontWeight.bold,
        fontSize: 10,
      ),
      headerDecoration: const pw.BoxDecoration(
        color: PdfThemeService.tableHeaderColor,
      ),
      cellStyle: pw.TextStyle(
        color: PdfThemeService.textColor,
        fontSize: 9,
      ),
      cellPadding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 8),
      cellAlignments: {
        for (var i = 0; i < headers.length; i++) 
          i: pw.Alignment.centerLeft
      },
      oddRowDecoration: const pw.BoxDecoration(
        color: PdfColor.fromInt(0xFFFAFAFA),
      ),
      columnWidths: columnWidths != null 
          ? { for (var i = 0; i < columnWidths.length; i++) i: pw.FlexColumnWidth(columnWidths[i]) }
          : null,
    );
  }
}
